name: CI Pipeline

on:
  push:
    branches:
      - '**' # Run on all branches
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: swapi
          POSTGRES_PASSWORD: password
          POSTGRES_DB: swapi
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for testing
        run: |
          docker build --build-arg NODE_ENV=development -t app:test .

      - name: Run tests inside Docker image
        run: |
          docker run --rm \
            --network host \
            -e DATABASE_URL=postgres://swapi:password@localhost:5432/swapi \
            app:test npm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: coverage/

      - name: Log in to ttl.sh
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "${{ secrets.TTL_SH_TOKEN }}" | docker login ttl.sh -u anonymous --password-stdin

      - name: Build and push release image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          IMAGE_NAME=ttl.sh/floatschedule-sre-assignment:${{ github.sha }}
          docker build --build-arg NODE_ENV=production -t $IMAGE_NAME .
          docker push $IMAGE_NAME